# Generated by Django 2.2.2 on 2019-06-24 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='imdb_rating',
            field=models.CharField(auto_created=True, max_length=10),
        ),
    ]
