# Generated by Django 2.2.2 on 2019-06-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating_api', '0002_auto_20190624_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='imdb_rating',
            field=models.CharField(max_length=10),
        ),
    ]
