# Generated by Django 2.2.2 on 2019-06-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating_api', '0004_auto_20190624_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='imdb_rating',
            field=models.CharField(blank=True, default=0, editable=False, max_length=10),
        ),
    ]
