# Generated by Django 2.2.2 on 2019-06-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating_api', '0005_auto_20190624_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='imdb_rating',
            field=models.CharField(blank=True, editable=False, max_length=10),
        ),
    ]
